TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

PROD_HOST += caExample
caExample_SRCS	+= caExample.c
caExample_LIBS	+= $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caMonitor
caMonitor_SRCS	+= caMonitor.c
caMonitor_LIBS	+= $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson1
caLesson1_SRCS += caLesson1.c
caLesson1_LIBS += $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson2
caLessoni2_SRCS += caLesson2.c
caLesson2_LIBS += $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson3
caLesson3_SRCS += caLesson3.c
caLesson3_LIBS += $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson4a
caLesson4a_SRCS += caLesson4a.c
caLesson4a_LIBS += $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson4b
caLesson4b_SRCS += caLesson4b.c
caLesson4b_LIBS += $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson5a
caLesson5a_SRCS += caLesson5a.c
caLesson5a_LIBS += $(EPICS_BASE_HOST_LIBS)

PROD_HOST += caLesson5b
caLesson5b_SRCS += caLesson5b.c
caLesson5b_LIBS += $(EPICS_BASE_HOST_LIBS)
include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

